keys:
  - &users
    - &jonathan age16aplnryhd34d56fyyvz0p2qlrh74tlffug4ffzlrlau0wwd75ylsl7wcyj
  - &hosts
    - &turing
    - &ritchie
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *jonathan
